version: 1.0.{build}
image: Ubuntu2004
environment:
  nodejs_version: "16"
  GITHUB_AUTH_TOKEN:
    secure: 2YjVzBsSXLSSFG4rX5qAPqRr2vbfr1EcYFeIwAdV6hZyCVFcoV2PNG3R/BbdeJf7
install:
  - nvm install $nodejs_version
  - npm install
build_script:
  - npm run build
artifacts:
  - path: dist
    name: build
deploy:
  provider: GitHub
  artifact: dist
  auth_token: $(GITHUB_AUTH_TOKEN)
  tag: $(APPVEYOR_BUILD_VERSION)
  description: "Release $(APPVEYOR_BUILD_VERSION)"
  draft: false
  prerelease: false
  on:
    branch: main